printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0  
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0  
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0  
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0  
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
printf "hello\n" > /dev/ttyACM0 
