TOOLCHAIN_BASE := ./
MODULES_BASE := ../../

SDK_CLOSED := ./bsp/esp_1_4_0/
SDK_BASE := ../../modules/modules_1_4_0/
CUSTOM_LIBS := 
LIBS :=  c gcc gcov hal pp phy net80211 lwip wpa ssl main driver
OPTIMIZE_FLAG = -c  ## ANY VALUE OVERWRITES -O2
CFLAGS := -Werror

include ../../Makefile
