TOOLCHAIN_BASE := ./
MODULES_BASE := ../../

SDK_CLOSED := ./bsp/esp_rtos/
SDK_BASE := ../../modules/modules_rtos/
CUSTOM_LIBS := uart_custom
LIBS :=  minic  gcc gcov hal pp phy net80211 freertos lwip wpa ssl main driver


	
CFLAGS := -Werror

include ../../Makefile
