TOOLCHAIN_BASE := ./
MODULES_BASE := ../../

SDK_CLOSED := ./bsp/esp_1_2_0/
SDK_BASE := ../../modules/modules_1_2_0/
CUSTOM_LIBS := 
LIBS :=  c gcc gcov hal pp phy net80211 lwip wpa ssl main driver

CFLAGS := -Werror

include ../../Makefile
